import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import {
  faGraduationCap,
  faBriefcase,
  faUserTie,
  faUsers,
  faIdCard,
  faFileAlt,
  faClipboardCheck,
  faClipboardList,
  faCalendarAlt,
  faCalendarCheck,
  faClock,
  faHourglassHalf,
  faStopwatch,
  faBell,
  faBullseye,
  faCheckCircle,
  faTimesCircle,
  faExclamationCircle,
  faExclamationTriangle,
  faInfoCircle,
  faMapMarkerAlt,
  faBuilding,
  faUniversity,
  faLandmark,
  faBook,
  faBookOpen,
  faPencilAlt,
  faLaptop,
  faDesktop,
  faMoneyBillWave,
  faCoins,
  faChartLine,
  faChartBar,
  faPollH,
  faTrophy,
  faMedal,
  faAward,
  faStar,
  faFlag,
  faRocket,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faLock,
  faUnlock,
  faShieldAlt,
  faGavel,
  faBalanceScale,
  faStethoscope,
  faTools,
  faWrench,
  faCogs,
  faTruck,
  faTrain,
  faPlane,
  faShip,
} from '@fortawesome/free-solid-svg-icons'

export interface IconOption {
  name: string
  icon: IconDefinition
}

export const ICON_OPTIONS: IconOption[] = [
  { name: 'graduation-cap', icon: faGraduationCap },
  { name: 'briefcase', icon: faBriefcase },
  { name: 'user-tie', icon: faUserTie },
  { name: 'users', icon: faUsers },
  { name: 'id-card', icon: faIdCard },
  { name: 'file-alt', icon: faFileAlt },
  { name: 'clipboard-check', icon: faClipboardCheck },
  { name: 'clipboard-list', icon: faClipboardList },
  { name: 'calendar-alt', icon: faCalendarAlt },
  { name: 'calendar-check', icon: faCalendarCheck },
  { name: 'clock', icon: faClock },
  { name: 'hourglass-half', icon: faHourglassHalf },
  { name: 'stopwatch', icon: faStopwatch },
  { name: 'bell', icon: faBell },
  { name: 'bullseye', icon: faBullseye },
  { name: 'check-circle', icon: faCheckCircle },
  { name: 'times-circle', icon: faTimesCircle },
  { name: 'exclamation-circle', icon: faExclamationCircle },
  { name: 'exclamation-triangle', icon: faExclamationTriangle },
  { name: 'info-circle', icon: faInfoCircle },
  { name: 'map-marker-alt', icon: faMapMarkerAlt },
  { name: 'building', icon: faBuilding },
  { name: 'university', icon: faUniversity },
  { name: 'landmark', icon: faLandmark },
  { name: 'book', icon: faBook },
  { name: 'book-open', icon: faBookOpen },
  { name: 'pencil-alt', icon: faPencilAlt },
  { name: 'laptop', icon: faLaptop },
  { name: 'desktop', icon: faDesktop },
  { name: 'money-bill-wave', icon: faMoneyBillWave },
  { name: 'coins', icon: faCoins },
  { name: 'chart-line', icon: faChartLine },
  { name: 'chart-bar', icon: faChartBar },
  { name: 'poll-h', icon: faPollH },
  { name: 'trophy', icon: faTrophy },
  { name: 'medal', icon: faMedal },
  { name: 'award', icon: faAward },
  { name: 'star', icon: faStar },
  { name: 'flag', icon: faFlag },
  { name: 'rocket', icon: faRocket },
  { name: 'arrow-right', icon: faArrowRight },
  { name: 'arrow-up', icon: faArrowUp },
  { name: 'arrow-down', icon: faArrowDown },
  { name: 'lock', icon: faLock },
  { name: 'unlock', icon: faUnlock },
  { name: 'shield-alt', icon: faShieldAlt },
  { name: 'gavel', icon: faGavel },
  { name: 'balance-scale', icon: faBalanceScale },
  { name: 'stethoscope', icon: faStethoscope },
  { name: 'tools', icon: faTools },
  { name: 'wrench', icon: faWrench },
  { name: 'cogs', icon: faCogs },
  { name: 'truck', icon: faTruck },
  { name: 'train', icon: faTrain },
  { name: 'plane', icon: faPlane },
  { name: 'ship', icon: faShip },
]

const ICON_BY_NAME = new Map(ICON_OPTIONS.map((opt) => [opt.name, opt.icon]))

export function getIconByName(name: string | null | undefined): IconDefinition | undefined {
  if (!name) return undefined
  return ICON_BY_NAME.get(name)
}
